DROP TABLE IF EXISTS Accounts;
CREATE TABLE `Accounts` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`username` VARCHAR( 255 ) NOT NULL ,
`password` VARCHAR( 255 ) NOT NULL ,
`email` VARCHAR( 255 ) NOT NULL ,
`level` INT NOT NULL ,
UNIQUE (username)
)ENGINE = INNODB;